language: android
android:
  components:
    - build-tools-23.0.0
    - android-23
    
before_install:
 - chmod +x gradlew
 
deploy:
  provider: releases
  user: "passiondroid"
  password: "India@123"
  file: "/app/build/outputs/app-release.apk"
  skip_cleanup: true
  on:
    tags: true
